version: '3'

services:
  redis:
    image: redis:alpine
    container_name: dummy_redis_container
  
  web:
    image: busybox
    container_name: dummy_hello_word
    command: ["echo", "busybox"]
  